### ISSUE TITLE
Installazione composer

### ISSUE THREAD

**Issue by ceccoudine** [fatturaelettronicaphp/sender-aruba#1]
Cercando di installare tramite composer restituisce errore:
```
 [InvalidArgumentException]                                                   
  Could not find a matching version of package fatturaelettronicaphp/sender-a  
  ruba. Check the package spelling, your version constraint and that the pack  
  age is available in a stability which matches your minimum-stability (stabl  
  e).   
```
<img width="1440" alt="Schermata 2022-09-29 alle 21 24 39" src="https://user-images.githubusercontent.com/78864466/193124179-4cf9c05a-0318-4c94-89a9-69135976a432.png">

**Comment by Skullbock** [comment]
La libreria non è ancora pubblicata su composer, avendola testata solo io.
Puoi provare a installarla aggiungendo questo repository al composer.json

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by ceccoudine** [comment]
Perdonami, non sono molto pratico, ti allego il file. Così? Poi devo lanciare il comando:
composer require fatturaelettronicaphp/sender-aruba ?
Grazie
<img width="414" alt="Schermata 2022-09-30 alle 13 49 20" src="https://user-images.githubusercontent.com/78864466/193263368-cd933638-6d48-4949-a63f-a94de112384d.png">

**Comment by Skullbock** [comment]
No, così:

```json
{
    "repositories": [{
         "type": "vcs",
          "url": "git@github.com:fatturaelettronicaphp/sender-aruba.git"
     }],
     "require": {
         "fatturaelettronicaphp/sender-aruba": "dev-main"
      }
}
```
